/**
 * Per-zone placement rules — transcribed 2026-09-03 from the practitioner's own
 * MahaVastu coursebook reference charts (rules/ folder, kept local & unpublished).
 * Every entry paraphrases the chart's reading for THAT item in THAT zone, so the
 * analysis can predict per direction instead of reciting a generic rule.
 *
 * v: how the chart reads that seat.  t: the effect, condensed to a sentence.
 * A zone missing from a kind's table means the source chart didn't cover it —
 * consumers fall back to the generic PlacementRule wording.
 *
 * PLACEMENT_RULES in vastu.ts is DERIVED from these tables (ideal/good/caution/
 * avoid lists), so the whole app — findings, zone card, report — follows the
 * charts automatically. Kinds with no chart here (bed, dressing) keep their
 * hand-written classical rules in vastu.ts.
 */

export type ZoneKey =
  | 'N' | 'NNE' | 'NE' | 'ENE' | 'E' | 'ESE' | 'SE' | 'SSE'
  | 'S' | 'SSW' | 'SW' | 'WSW' | 'W' | 'WNW' | 'NW' | 'NNW'

export type RuleVerdict = 'ideal' | 'good' | 'neutral' | 'caution' | 'avoid'

export interface ZoneEffect { v: RuleVerdict; t: string }

type Table = Partial<Record<ZoneKey, ZoneEffect>>

export const ZONE_RULES: Record<string, Table> = {
  kitchen: {
    N:   { v: 'avoid',   t: 'career growth and sales suffer; food cooked here loses its taste' },
    NNE: { v: 'avoid',   t: 'invites recurring health troubles and constant medication' },
    NE:  { v: 'avoid',   t: 'clouds the mind — confusion and brain-related ailments' },
    ENE: { v: 'caution', t: 'the family chases fun it never quite gets' },
    E:   { v: 'neutral', t: 'average for money and social life (fine for religious buildings)' },
    ESE: { v: 'avoid',   t: 'continual family clashes; male health suffers over time' },
    SE:  { v: 'good',    t: 'cash in hand and zeal improve, with a touch more aggression' },
    SSE: { v: 'ideal',   t: 'the fire seat — strength, confidence and delicious healthy food' },
    S:   { v: 'good',    t: 'brings recognition and a relaxed, comfortable life' },
    SSW: { v: 'avoid',   t: 'father–son clashes, rising expenses and health hazards' },
    SW:  { v: 'avoid',   t: 'skills go unused — career instability and strained relations' },
    WSW: { v: 'caution', t: 'savings drain and children struggle for marks' },
    W:   { v: 'ideal',   t: 'continuous gains of money and good family health' },
    WNW: { v: 'caution', t: 'complaints brew between the couple; otherwise workable' },
    NW:  { v: 'caution', t: 'support from others becomes harder to get' },
    NNW: { v: 'caution', t: 'disturbs intimacy between the couple' },
  },

  toilet: {
    N:   { v: 'avoid',   t: 'career problems — opportunities to earn shrink away' },
    NNE: { v: 'avoid',   t: 'poor immunity; illness returns and recovery is slow' },
    NE:  { v: 'avoid',   t: 'the most serious seat — health, memory and wisdom drain away' },
    ENE: { v: 'avoid',   t: 'lethargy and heaviness; the family never feels refreshed' },
    E:   { v: 'avoid',   t: 'social circles shrink and society stops noticing you' },
    ESE: { v: 'good',    t: 'flushes out anxiety and over-analysis — a favourable seat' },
    SE:  { v: 'avoid',   t: 'obstacles and cash crunch; auspicious events get blocked' },
    SSE: { v: 'avoid',   t: 'saps confidence, strength and drive' },
    S:   { v: 'avoid',   t: 'desperate for recognition; goodwill suffers' },
    SSW: { v: 'ideal',   t: 'the disposal seat itself — washes negativity out of your life' },
    SW:  { v: 'avoid',   t: 'family relationships and stability get disturbed' },
    WSW: { v: 'avoid',   t: 'savings leak and children avoid their studies' },
    W:   { v: 'avoid',   t: 'blocks profitable growth despite sincere effort' },
    WNW: { v: 'good',    t: 'releases blocked emotions — an acceptable seat' },
    NW:  { v: 'avoid',   t: 'help and support dry up; bank balance dips' },
    NNW: { v: 'avoid',   t: 'attraction between the couple fades' },
  },

  septic: {
    N:   { v: 'avoid',   t: 'career-related problems; earning opportunities fade' },
    NNE: { v: 'avoid',   t: 'poor immunity — frequent seasonal illness' },
    NE:  { v: 'avoid',   t: 'major health troubles; clarity and wisdom suffer' },
    ENE: { v: 'avoid',   t: 'lethargy and heaviness in the whole family' },
    E:   { v: 'avoid',   t: 'social connections weaken' },
    ESE: { v: 'good',    t: 'a favourable seat — reduces anxiety and over-analysis' },
    SE:  { v: 'avoid',   t: 'blocks inflow of money; a permanent cash crunch' },
    SSE: { v: 'avoid',   t: 'drains confidence and physical strength' },
    S:   { v: 'avoid',   t: 'tension and desperation for fame; goodwill suffers' },
    SSW: { v: 'ideal',   t: 'the best seat — disposal belongs here and harms nothing' },
    SW:  { v: 'avoid',   t: 'family bonds and life stability get shaken' },
    WSW: { v: 'avoid',   t: 'savings and children’s studies suffer' },
    W:   { v: 'avoid',   t: 'gains stay small no matter the effort' },
    WNW: { v: 'good',    t: 'helps release blocked emotions — acceptable' },
    NW:  { v: 'avoid',   t: 'support and bank balance both reduce' },
    NNW: { v: 'avoid',   t: 'the couple drifts apart' },
  },

  living: {
    N:   { v: 'good',    t: 'conversations open new money opportunities' },
    NNE: { v: 'good',    t: 'visitors bring tips for better health' },
    NE:  { v: 'neutral', t: 'discussions lean to religious matters and religious contacts' },
    ENE: { v: 'good',    t: 'guests are well entertained; happy family meetings' },
    E:   { v: 'ideal',   t: 'the perfect seat — social bonds formed here last' },
    ESE: { v: 'avoid',   t: 'meetings churn without reaching any conclusion' },
    SE:  { v: 'caution', t: 'results come, but discussions run heated' },
    SSE: { v: 'good',    t: 'agreements come easily; talks stay graceful' },
    S:   { v: 'good',    t: 'relaxed, easy meetings' },
    SSW: { v: 'avoid',   t: 'the disposal band — money leaks through this room' },
    SW:  { v: 'neutral', t: 'talk turns to family, ancestors and stability' },
    WSW: { v: 'neutral', t: 'education and government matters dominate' },
    W:   { v: 'good',    t: 'productive, fruitful meetings' },
    WNW: { v: 'caution', t: 'guests hear a stream of problems and complaints' },
    NW:  { v: 'good',    t: 'negotiations settle in your favour; help is hard to refuse' },
    NNW: { v: 'caution', t: 'you keep helping others with little return' },
  },

  dining: {
    N:   { v: 'good',    t: 'career focus sharpens over meals; digestion runs a little weak' },
    NNE: { v: 'good',    t: 'health-conscious eating — good health follows' },
    NE:  { v: 'caution', t: 'appetite turns ascetic — fasting and food restrictions grow' },
    ENE: { v: 'caution', t: 'children slide toward junk food; elders turn to diets' },
    E:   { v: 'good',    t: 'meals become social — friends join the table' },
    ESE: { v: 'avoid',   t: 'anxious, fault-finding meals and quarrels' },
    SE:  { v: 'caution', t: 'appetite and digestion improve, aggression rises with them' },
    SSE: { v: 'ideal',   t: 'food digests well and heals — nutrients truly land' },
    S:   { v: 'good',    t: 'meals bring peace of mind' },
    SSW: { v: 'avoid',   t: 'the family avoids this table; food gives no strength' },
    SW:  { v: 'avoid',   t: 'disharmony and scolding at every meal' },
    WSW: { v: 'neutral', t: 'table manners and etiquette take centre stage' },
    W:   { v: 'ideal',   t: 'the purpose of dining fulfilled — net gains and good health' },
    WNW: { v: 'avoid',   t: 'constant complaining about the food breeds negativity' },
    NW:  { v: 'good',    t: 'support arrives when needed; desires get fulfilled' },
    NNW: { v: 'good',    t: 'works as an appetizer — everyone loves trying new dishes' },
  },

  lounge: {
    N:   { v: 'good',    t: 'family talk turns to careers and growth' },
    NNE: { v: 'good',    t: 'the family grows health-conscious together' },
    NE:  { v: 'good',    t: 'fruitful brainstorming and spiritual discussions' },
    ENE: { v: 'good',    t: 'quality time that genuinely refreshes' },
    E:   { v: 'good',    t: 'social talk — neighbours, lifestyle, growth' },
    ESE: { v: 'caution', t: 'endless detail over trifles; quarrels if the zone is off' },
    SE:  { v: 'caution', t: 'discussions run heated though affection stays' },
    SSE: { v: 'good',    t: 'low moods lift here — the family draws strength together' },
    S:   { v: 'good',    t: 'a place to relax and nap more than debate' },
    SSW: { v: 'avoid',   t: 'interest in sitting together gradually dies' },
    SW:  { v: 'good',    t: 'deep respect for elders and ancestors takes root' },
    WSW: { v: 'good',    t: 'knowledge and experience flow between generations' },
    W:   { v: 'neutral', t: 'talk turns material — wealth, savings, profits' },
    WNW: { v: 'avoid',   t: 'catharsis tips into weeping — better avoided' },
    NW:  { v: 'good',    t: 'ensures timely family support, especially financial' },
    NNW: { v: 'good',    t: 'the family simply enjoys sitting together' },
  },

  study: {
    N:   { v: 'good',    t: 'career-oriented studies thrive (management, civil services)' },
    NNE: { v: 'neutral', t: 'inclination toward medicine and ayurveda' },
    NE:  { v: 'good',    t: 'research work — new ideas and insights arrive' },
    ENE: { v: 'avoid',   t: 'books feel like a burden; comics win' },
    E:   { v: 'neutral', t: 'draws the student toward political science' },
    ESE: { v: 'avoid',   t: 'over-analysis erodes grasping power' },
    SE:  { v: 'neutral', t: 'draws the student toward law and criminology' },
    SSE: { v: 'neutral', t: 'sports and physical education take priority' },
    S:   { v: 'caution', t: 'too relaxed — the child studies sleepily' },
    SSW: { v: 'avoid',   t: 'effort proves futile; poor grades or failure' },
    SW:  { v: 'good',    t: 'skill-based studies succeed here' },
    WSW: { v: 'ideal',   t: 'the school student’s seat — natural inclination, excellent grades' },
    W:   { v: 'good',    t: 'every effort pays; accountancy especially' },
    WNW: { v: 'avoid',   t: 'studies become stress and low mood — keep the desk out' },
    NW:  { v: 'good',    t: 'administration and management studies do well' },
    NNW: { v: 'avoid',   t: 'films and distractions replace the books' },
  },

  store: {
    N:   { v: 'avoid',   t: 'mixed stored metals hamper career and money flow' },
    NNE: { v: 'avoid',   t: 'stored clutter here tells on the family’s health' },
    NE:  { v: 'avoid',   t: 'blocks the zone of clarity — indecision and dilemmas' },
    ENE: { v: 'avoid',   t: 'lethargy; joy feels out of reach at celebrations' },
    E:   { v: 'avoid',   t: 'social connectivity suffers' },
    ESE: { v: 'good',    t: 'a store here quiets anxiety and unwanted thoughts' },
    SE:  { v: 'caution', t: 'slows money inflow (though it protects a service job)' },
    SSE: { v: 'good',    t: 'gives a feeling of power, confidence and security' },
    S:   { v: 'good',    t: 'relaxes the mind; earned standing protects you' },
    SSW: { v: 'good',    t: 'the seat for true waste — never store valuables here' },
    SW:  { v: 'caution', t: 'only valuables and the tools of your skill — junk here hurts' },
    WSW: { v: 'good',    t: 'useful goods stored here build children’s values and focus' },
    W:   { v: 'good',    t: 'secured gains — the right seat for the iron safe' },
    WNW: { v: 'good',    t: 'stores away low moods; inner confidence grows' },
    NW:  { v: 'ideal',   t: 'the ideal store — any goods; banking and helpful people multiply' },
    NNW: { v: 'caution', t: 'organised storage only — junk here strains the marriage' },
  },

  servant: {
    N:   { v: 'avoid',   t: 'constant demands for raises; may leave — or steal' },
    NNE: { v: 'neutral', t: 'stays on, but minds their own health first' },
    NE:  { v: 'good',    t: 'loyal and enduring, though forgetful of instructions' },
    ENE: { v: 'neutral', t: 'fun-loving and cheerful, fond of the television' },
    E:   { v: 'avoid',   t: 'a stream of idle visitors wastes everyone’s time' },
    ESE: { v: 'caution', t: 'stays long but bends the truth' },
    SE:  { v: 'ideal',   t: 'busy, loyal and content — the classical servant seat' },
    SSE: { v: 'good',    t: 'fast, efficient work; real added strength' },
    S:   { v: 'good',    t: 'values respect over money and acts loyally' },
    SSW: { v: 'avoid',   t: 'their health suffers; they feel worthless here' },
    SW:  { v: 'good',    t: 'skills sharpen; a lasting bond with the household' },
    WSW: { v: 'good',    t: 'keeps learning and improving through practice' },
    W:   { v: 'neutral', t: 'suits cooks only' },
    WNW: { v: 'caution', t: 'complains over trifles yet never leaves' },
    NW:  { v: 'good',    t: 'always something on their mind, yet stands by you' },
    NNW: { v: 'avoid',   t: 'will not stay long' },
  },

  guest: {
    N:   { v: 'avoid',   t: 'a revolving door of short-stay guests disrupts life' },
    NNE: { v: 'good',    t: 'a safe seat — no good or bad effects' },
    NE:  { v: 'good',    t: 'guests are honoured — atithi devo bhavah' },
    ENE: { v: 'good',    t: 'guests leave rejuvenated and cheerful' },
    E:   { v: 'good',    t: 'strengthens your bond with visitors' },
    ESE: { v: 'avoid',   t: 'guests cut their stay short — use only to discourage them' },
    SE:  { v: 'avoid',   t: 'blocks money inflow, especially money you have lent' },
    SSE: { v: 'good',    t: 'you feel secure and strong with guests around' },
    S:   { v: 'avoid',   t: 'recognition of your efforts suffers' },
    SSW: { v: 'avoid',   t: 'the disposal band — visits fail their purpose, relations strain' },
    SW:  { v: 'good',    t: 'suits guests from the paternal side; relations improve' },
    WSW: { v: 'good',    t: 'brings you closer to your guests' },
    W:   { v: 'avoid',   t: 'your gains turn temporary' },
    WNW: { v: 'good',    t: 'no negativity — guests hold no grudges' },
    NW:  { v: 'avoid',   t: 'help and support get harder to find' },
    NNW: { v: 'caution', t: 'family guests only — avoid outsiders here' },
  },

  bar: {
    NE:  { v: 'avoid',   t: 'distraction and instability of mind' },
    ENE: { v: 'caution', t: 'drinking becomes the only definition of joy' },
    E:   { v: 'avoid',   t: 'creates distance in social relationships' },
    ESE: { v: 'good',    t: 'a permitted seat — softens anxiety, keeps things cordial' },
    SE:  { v: 'avoid',   t: 'money drains; effort dissolves like drinking after drinking' },
    SSE: { v: 'avoid',   t: 'breeds low confidence and inferiority' },
    S:   { v: 'avoid',   t: 'sleep disorders and lost peace of mind' },
    SSW: { v: 'caution', t: 'the urge fades — and so does liveliness' },
    SW:  { v: 'avoid',   t: 'skills stop being used properly' },
    WSW: { v: 'avoid',   t: 'children’s focus and study suffer' },
    W:   { v: 'good',    t: 'improves gains for the family — a good seat' },
  },

  staircase: {
    N:   { v: 'neutral', t: 'run it anticlockwise here — it opens career growth' },
    NNE: { v: 'neutral', t: 'anticlockwise here strengthens immunity and recovery' },
    NE:  { v: 'neutral', t: 'anticlockwise brings clarity and new ideas; clockwise suppresses them' },
    ENE: { v: 'neutral', t: 'anticlockwise multiplies joy and fun' },
    E:   { v: 'neutral', t: 'anticlockwise here makes social relations profitable' },
    ESE: { v: 'neutral', t: 'clockwise calms the churning mind; anticlockwise feeds it' },
    SE:  { v: 'neutral', t: 'clockwise reins in anger; anticlockwise inflames it' },
    SSE: { v: 'neutral', t: 'anticlockwise builds strength and confidence' },
    S:   { v: 'neutral', t: 'clockwise brings fame; anticlockwise a bad name' },
    SSW: { v: 'neutral', t: 'always clockwise here — it cuts waste and lifts efficiency' },
    SW:  { v: 'neutral', t: 'clockwise steadies career, relationships and skills' },
    WSW: { v: 'neutral', t: 'clockwise channels practice into results' },
    W:   { v: 'neutral', t: 'anticlockwise multiplies material gains' },
    WNW: { v: 'neutral', t: 'clockwise keeps emotions balanced' },
    NW:  { v: 'neutral', t: 'clockwise draws help and support when needed' },
    NNW: { v: 'neutral', t: 'anticlockwise deepens the couple’s bond' },
  },

  guard: {
    N:   { v: 'avoid',   t: 'hindrances for the owner; guards refuse to stay' },
    NNE: { v: 'neutral', t: 'a permissible seat' },
    NE:  { v: 'caution', t: 'workable, but the guard loses alertness' },
    ENE: { v: 'avoid',   t: 'the guard makes fun of the job' },
    E:   { v: 'avoid',   t: 'strangers sway him; he plays the leader' },
    ESE: { v: 'good',    t: 'the guard stays concerned to perform better' },
    SE:  { v: 'ideal',   t: 'all-round security for the whole house' },
    SSE: { v: 'good',    t: 'the power seat strengthens your security' },
    S:   { v: 'good',    t: 'security concerns dissolve' },
    SSW: { v: 'avoid',   t: 'disposes of your security — regular thefts' },
    SW:  { v: 'good',    t: 'the guard grows skilful at his duty' },
    WSW: { v: 'good',    t: 'uses knowledge and wits to protect you' },
    W:   { v: 'avoid',   t: 'always hunting a new job — retention fails' },
    WNW: { v: 'neutral', t: 'a permissible seat' },
    NW:  { v: 'good',    t: 'the backup-support seat — a natural fit' },
    NNW: { v: 'avoid',   t: 'attention drifts from the job' },
  },

  pet: {
    N:   { v: 'neutral', t: 'pets can be kept here' },
    NNE: { v: 'neutral', t: 'a permissible seat' },
    NE:  { v: 'avoid',   t: 'low moods at home; the pet weakens quickly' },
    ENE: { v: 'good',    t: 'pets stay healthy and active' },
    E:   { v: 'good',    t: 'pets stay healthy' },
    ESE: { v: 'neutral', t: 'no adverse effects' },
    SE:  { v: 'caution', t: 'pets stay irritable here' },
    SSE: { v: 'ideal',   t: 'alert and healthy — the best seat for pets' },
    S:   { v: 'neutral', t: 'a permissible seat' },
    SSW: { v: 'avoid',   t: 'recurring troubles; the pet drifts out of your life' },
    SW:  { v: 'good',    t: 'quick to understand commands, fast to train' },
    WSW: { v: 'neutral', t: 'a permissible seat' },
    W:   { v: 'neutral', t: 'a permissible seat' },
    WNW: { v: 'avoid',   t: 'keeping them here brings tears' },
    NW:  { v: 'neutral', t: 'pets can be kept here' },
    NNW: { v: 'good',    t: 'the pet becomes the centre of attention' },
  },

  tv: {
    N:   { v: 'good',    t: 'sharpens career vision — new avenues open' },
    NNE: { v: 'caution', t: 'health-channel obsession that erodes health' },
    NE:  { v: 'caution', t: 'watching about meditation replaces doing it' },
    ENE: { v: 'ideal',   t: 'the entertainment seat — fun, energy, refreshment' },
    E:   { v: 'good',    t: 'awareness and social connectivity improve' },
    ESE: { v: 'good',    t: 'stress finds its answers on screen' },
    SE:  { v: 'neutral', t: 'draws the eye to money programmes and thrillers' },
    SSE: { v: 'good',    t: 'strength and fitness programmes dominate' },
    S:   { v: 'good',    t: 'complete relaxation and sound sleep' },
    SSW: { v: 'avoid',   t: 'wasted hours, bad decisions and constant repairs' },
    SW:  { v: 'good',    t: 'works as a skill enhancer' },
    WSW: { v: 'caution', t: 'cartoons beat homework — allow only educational viewing' },
    W:   { v: 'good',    t: 'gainful information, a boon for traders' },
    WNW: { v: 'avoid',   t: 'melancholy viewing; tears flow easily' },
    NW:  { v: 'good',    t: 'naturally attracts support for your causes' },
    NNW: { v: 'avoid',   t: 'pulls viewing toward the explicit' },
  },

  computer: {
    N:   { v: 'good',    t: 'best used for career growth and new opportunities' },
    NNE: { v: 'good',    t: 'good for gathering health information' },
    NE:  { v: 'good',    t: 'suits creative work, new ideas and devotional use' },
    ENE: { v: 'good',    t: 'the games-and-music seat — pure enjoyment' },
    E:   { v: 'good',    t: 'connects you with the world around' },
    ESE: { v: 'good',    t: 'data entry, heavy calculation and research thrive' },
    SE:  { v: 'ideal',   t: 'ideal for maintaining the cash balance' },
    SSE: { v: 'good',    t: 'long working hours without fatigue' },
    S:   { v: 'good',    t: 'work done here fetches admiration and fame' },
    SSW: { v: 'avoid',   t: 'lies unused, breaks often; share-trading losses' },
    SW:  { v: 'good',    t: 'skilful work like designing excels' },
    WSW: { v: 'good',    t: 'knowledge and education; accountancy especially' },
    W:   { v: 'good',    t: 'information turns beneficial — good for share business' },
    WNW: { v: 'good',    t: 'counters low mood, stress and depression' },
    NW:  { v: 'good',    t: 'timely support arrives through your contacts' },
    NNW: { v: 'avoid',   t: 'invites undesired surfing — keep children away' },
  },

  washing: {
    N:   { v: 'caution', t: 'churns career thoughts — stay or switch, endlessly' },
    NNE: { v: 'caution', t: 'fussiness about food chips away at health' },
    NE:  { v: 'avoid',   t: 'anxious over-analysis of trifles; headaches' },
    ENE: { v: 'caution', t: 'one worry or another shadows every pleasure' },
    E:   { v: 'caution', t: 'endless churning over image and society' },
    ESE: { v: 'ideal',   t: 'churning belongs here — a calm mind, good decisions' },
    SE:  { v: 'caution', t: 'thoughts circle hard cash and how to make more' },
    SSE: { v: 'caution', t: 'preoccupation with healing and self-confidence' },
    S:   { v: 'caution', t: 'analysis continues even in bed — restless sleep' },
    SSW: { v: 'avoid',   t: 'trivial analysis, losing decisions, frequent repairs' },
    SW:  { v: 'avoid',   t: 'churning over family matters breeds feuds' },
    WSW: { v: 'caution', t: 'overcaution slows everyone, especially children' },
    W:   { v: 'caution', t: 'desperation for gains that never materialise' },
    WNW: { v: 'good',    t: 'clears mental clutter along with the clothes' },
    NW:  { v: 'good',    t: 'supportive people — and banks — cooperate' },
    NNW: { v: 'avoid',   t: 'churning disturbs the couple’s intimacy' },
  },

  dustbin: {
    N:   { v: 'avoid',   t: 'blocks new career opportunities and payment recovery' },
    NNE: { v: 'avoid',   t: 'attracts disease and endless medication' },
    NE:  { v: 'avoid',   t: 'confusion and lost vision — goals blur' },
    ENE: { v: 'avoid',   t: 'laziness; the past replays instead of refreshing' },
    E:   { v: 'avoid',   t: 'the cocoon closes — society stops mattering' },
    ESE: { v: 'good',    t: 'a good seat — reins in excessive thinking' },
    SE:  { v: 'avoid',   t: 'the root of blocked payments and cash starvation' },
    SSE: { v: 'avoid',   t: 'power, confidence and vitality leak away' },
    S:   { v: 'avoid',   t: 'restless nights; hard work goes unappreciated' },
    SSW: { v: 'ideal',   t: 'the ideal seat — negativity leaves with the waste' },
    SW:  { v: 'avoid',   t: 'relationships start feeling disposable' },
    WSW: { v: 'avoid',   t: 'savings and children’s concentration suffer' },
    W:   { v: 'avoid',   t: 'results slip from your hand at the last moment' },
    WNW: { v: 'good',    t: 'low moods and blocked emotions go out with it' },
    NW:  { v: 'avoid',   t: 'help dries up when you need it most' },
    NNW: { v: 'avoid',   t: 'dissatisfaction seeps into the marriage' },
  },

  safe: {
    N:   { v: 'ideal',   t: 'Kubera’s seat — wealth grows; never leave it empty' },
    SW:  { v: 'good',    t: 'good for long-term valuables — never sunk under the floor' },
    WSW: { v: 'good',    t: 'iron safe here guards long-term valuables and grows gains' },
    W:   { v: 'good',    t: 'the iron locker seat — gains and profits accumulate' },
  },

  music: {
    N:   { v: 'good',    t: 'playing attracts new career opportunities' },
    NNE: { v: 'good',    t: 'music works as medicine here — mental healing' },
    NE:  { v: 'avoid',   t: 'the connection with music quietly dies' },
    ENE: { v: 'ideal',   t: 'the rejuvenation seat — music keeps life joyful' },
    E:   { v: 'good',    t: 'recommended for professionals — career growth' },
    ESE: { v: 'avoid',   t: 'instruments lie idle and faulty' },
    SE:  { v: 'good',    t: 'playing attracts money' },
    SSE: { v: 'good',    t: 'music adds strength and stage confidence' },
    S:   { v: 'good',    t: 'opens the deeper secrets of the art' },
    SSW: { v: 'good',    t: 'music becomes a medium of letting go' },
    SW:  { v: 'good',    t: 'skill and performance sharpen' },
    WSW: { v: 'good',    t: 'disciplined practice takes hold' },
    W:   { v: 'good',    t: 'the art starts paying — gains and friends' },
    WNW: { v: 'avoid',   t: 'learning stalls; disappointment creeps in' },
    NW:  { v: 'neutral', t: 'neither helps nor harms' },
    NNW: { v: 'caution', t: 'playing draws romantic attention' },
  },

  inverter: {
    N:   { v: 'avoid',   t: 'career grows dependent on others’ mercy' },
    NNE: { v: 'avoid',   t: 'respiratory troubles and medical emergencies' },
    NE:  { v: 'avoid',   t: 'mental clarity dims; decisions need borrowing' },
    ENE: { v: 'avoid',   t: 'life goes flat — refreshment stops working' },
    E:   { v: 'avoid',   t: 'constant asking for help erodes your image' },
    ESE: { v: 'good',    t: 'emergency help arrives (keep it maintained)' },
    SE:  { v: 'neutral', t: 'acceptable — but a defect disturbs liquid cash' },
    SSE: { v: 'caution', t: 'self-confidence starts leaning on others' },
    S:   { v: 'caution', t: 'a constant urge to relax that never lands' },
    SSW: { v: 'avoid',   t: 'no help when needed; the unit itself stays faulty' },
    SW:  { v: 'caution', t: 'reluctance to use one’s own skill' },
    WSW: { v: 'caution', t: 'students survive on borrowed notes' },
    W:   { v: 'caution', t: 'regular gains arrive only in trickles' },
    WNW: { v: 'good',    t: 'a shoulder to cry on, whenever needed' },
    NW:  { v: 'ideal',   t: 'the backup seat itself — timely support assured' },
    NNW: { v: 'caution', t: 'intimacy becomes stress relief, not joy' },
  },

  crockery: {
    N:   { v: 'avoid',   t: 'blocks new orders and due payments' },
    NNE: { v: 'avoid',   t: 'breathing troubles; immunity weakens' },
    NE:  { v: 'avoid',   t: 'clouds vision and fresh ideas' },
    ENE: { v: 'good',    t: 'adds enjoyment — beautiful serving, tasteful food' },
    E:   { v: 'good',    t: 'social connections quicken' },
    ESE: { v: 'avoid',   t: 'quarrels — and far too much breakage' },
    SE:  { v: 'good',    t: 'attracts money; hard work returns as cash' },
    SSE: { v: 'good',    t: 'a feeling of power, confidence and security' },
    S:   { v: 'good',    t: 'relaxed minds; meals served in the best crockery' },
    SSW: { v: 'avoid',   t: 'rarely used — and stomach ailments when it is' },
    SW:  { v: 'good',    t: 'presentation skills lift career and stability' },
    WSW: { v: 'avoid',   t: 'children’s focus on studies breaks' },
    W:   { v: 'good',    t: 'gains and profits improve — a good seat' },
    WNW: { v: 'good',    t: 'inner confidence; low moods stay away' },
    NW:  { v: 'good',    t: 'support arrives in the hour of need' },
    NNW: { v: 'avoid',   t: 'dissatisfaction strains the marriage' },
  },

  heater: {
    N:   { v: 'avoid',   t: 'burns career openings; customers and payments elude' },
    NNE: { v: 'avoid',   t: 'attracts disease and continuous medication' },
    NE:  { v: 'avoid',   t: 'confusion, hasty conclusions, short temper' },
    ENE: { v: 'avoid',   t: 'fun turns to aggression and frustration' },
    E:   { v: 'neutral', t: 'permissible — average results' },
    ESE: { v: 'avoid',   t: 'over-analysis boils into family clashes' },
    SE:  { v: 'ideal',   t: 'the fire seat — cash in hand and blocked payments recover' },
    SSE: { v: 'good',    t: 'power, confidence and physical strength' },
    S:   { v: 'good',    t: 'relaxing sleep and due appreciation' },
    SSW: { v: 'avoid',   t: 'wasteful expenditure; the unit barely helps' },
    SW:  { v: 'avoid',   t: 'heated arguments; career instability roots here' },
    WSW: { v: 'avoid',   t: 'savings and children’s marks both burn' },
    W:   { v: 'avoid',   t: 'hard work stops converting into results' },
    WNW: { v: 'good',    t: 'burns off blocked emotions and low moods' },
    NW:  { v: 'avoid',   t: 'people keep their distance when you need them' },
    NNW: { v: 'avoid',   t: 'passion turns to heated arguments' },
  },

  ac: {
    N:   { v: 'good',    t: 'no ill effects here' },
    NNE: { v: 'good',    t: 'a permissible seat' },
    NE:  { v: 'avoid',   t: 'brings anxiety and instability of mind' },
    ENE: { v: 'good',    t: 'can be placed here' },
    E:   { v: 'good',    t: 'a permissible seat, no bad effects' },
    ESE: { v: 'good',    t: 'a permissible seat' },
    SE:  { v: 'avoid',   t: 'cash liquidity problems; savings suffer' },
    SSE: { v: 'good',    t: 'no bad effects' },
    S:   { v: 'good',    t: 'fire-friendly — permissible' },
    SSW: { v: 'good',    t: 'a permissible seat' },
    SW:  { v: 'avoid',   t: 'comfort-craving creeps into work' },
    WSW: { v: 'good',    t: 'no bad effects' },
    W:   { v: 'good',    t: 'can be placed here' },
    WNW: { v: 'good',    t: 'a permissible seat' },
    NW:  { v: 'good',    t: 'can be placed here' },
    NNW: { v: 'good',    t: 'no bad effects' },
  },

  medicine: {
    NNE: { v: 'ideal',   t: 'the healing seat itself — medicines act quickly here' },
    NE:  { v: 'neutral', t: 'permissible for keeping medicines' },
    ENE: { v: 'neutral', t: 'can be used for medicines' },
    E:   { v: 'good',    t: 'no bad effects' },
    ESE: { v: 'avoid',   t: 'medicines stop showing their effect' },
    SE:  { v: 'caution', t: 'doses keep increasing before they help' },
    SSE: { v: 'caution', t: 'health starts depending on the daily pill' },
    S:   { v: 'caution', t: 'pills at the first sneeze — instant-relief habit' },
    SSW: { v: 'avoid',   t: 'effects vanish — must be avoided' },
    SW:  { v: 'neutral', t: 'can be kept here' },
    WSW: { v: 'neutral', t: 'can be kept here' },
    W:   { v: 'good',    t: 'a very good seat for the medicine box' },
    WNW: { v: 'avoid',   t: 'nervousness rises and the effect weakens' },
    NW:  { v: 'good',    t: 'support-zone medicines become the trusted resort' },
    NNW: { v: 'good',    t: 'generates good healing effects' },
  },

  open: {
    N:   { v: 'caution', t: 'expectations of career outrun skills' },
    NNE: { v: 'good',    t: 'strong immunity and better health' },
    NE:  { v: 'ideal',   t: 'open space here breeds clarity, new ideas and growth vision' },
    ENE: { v: 'avoid',   t: 'joy fades; the mind loops through old memories' },
    E:   { v: 'caution', t: 'the family withdraws from society' },
    ESE: { v: 'avoid',   t: 'thoughts that never conclude — stress and anxiety' },
    SE:  { v: 'avoid',   t: 'financial gains face hurdle after hurdle' },
    SSE: { v: 'caution', t: 'strength is chased but insecurity lingers' },
    S:   { v: 'caution', t: 'too many dreams; society misreads you' },
    SSW: { v: 'avoid',   t: 'losses and investments turning to bad debts' },
    SW:  { v: 'avoid',   t: 'unrealistic expectations strain bonds; marriages delay' },
    WSW: { v: 'good',    t: 'children practise more — excellent grades follow' },
    W:   { v: 'ideal',   t: 'the gains zone open — efforts convert to profit' },
    WNW: { v: 'good',    t: 'emotions stay balanced; blockages release easily' },
    NW:  { v: 'caution', t: 'helpfulness comes with over-expectation of returns' },
    NNW: { v: 'avoid',   t: 'fantasy inflates; married life suffers' },
  },

  water: {
    N:   { v: 'good',    t: 'water strengthens the money zone' },
    NNE: { v: 'good',    t: 'supports health and healing' },
    NE:  { v: 'ideal',   t: 'the classical seat — gains in wealth, fame and clarity' },
    ENE: { v: 'good',    t: 'a supportive water seat' },
    E:   { v: 'good',    t: 'strengthened by water features' },
    ESE: { v: 'avoid',   t: 'water against fire — losses and tension' },
    SE:  { v: 'avoid',   t: 'weakens the fire of cash — accidents and tight money' },
    SSE: { v: 'avoid',   t: 'clashes with the fire band — ill repute' },
    S:   { v: 'avoid',   t: 'water quenches recognition here' },
    SSW: { v: 'avoid',   t: 'water on earth — instability and losses' },
    SW:  { v: 'avoid',   t: 'undermines the stability corner' },
    WSW: { v: 'avoid',   t: 'earth zone — savings and studies suffer' },
    W:   { v: 'good',    t: 'a strengthened gains zone' },
    WNW: { v: 'caution', t: 'keep water features modest here' },
    NW:  { v: 'avoid',   t: 'water disturbs the support zone' },
    NNW: { v: 'caution', t: 'keep it modest — restlessness otherwise' },
  },

  pooja: {
    N:   { v: 'good',    t: 'the seat of Laxmi and Ganesha pujas — others are out of place' },
    NNE: { v: 'ideal',   t: 'Shiv and Dhanwantri worship here gives health and vitality' },
    NE:  { v: 'ideal',   t: 'the blessed seat — clarity and divine guidance' },
    ENE: { v: 'good',    t: 'prayer here recharges — stress lifts quickly' },
    E:   { v: 'good',    t: 'favours from seniors and authority flow' },
    ESE: { v: 'caution', t: 'restless prayer — though it sharpens investment sense' },
    SE:  { v: 'caution', t: 'only Durga worship suits this fire seat' },
    SSE: { v: 'caution', t: 'suits Hanuman worship alone — strength and courage' },
    S:   { v: 'caution', t: 'Kali worship and deep meditation only' },
    SSW: { v: 'avoid',   t: 'prayer here brings losses — the chart reserves it for Aghori sadhana' },
    SW:  { v: 'caution', t: 'ancestor and Vishwakarma worship only; other pujas slow recoveries' },
    WSW: { v: 'caution', t: 'Saraswati’s seat — knowledge worship only' },
    W:   { v: 'ideal',   t: 'the Guru’s seat — abundance and every financial gain' },
    WNW: { v: 'caution', t: 'Yakshini sadhana alone belongs here' },
    NW:  { v: 'good',    t: 'the ideal seat for ancestral (pitra) rituals' },
    NNW: { v: 'caution', t: 'tantra practices only — not the household altar' },
  },
}

/** The chart's own line for this item in this zone — or null when uncovered. */
export function zoneEffect(kind: string, zoneKey: string): string | null {
  return ZONE_RULES[kind]?.[zoneKey as ZoneKey]?.t ?? null
}

export function zoneVerdict(kind: string, zoneKey: string): RuleVerdict | null {
  return ZONE_RULES[kind]?.[zoneKey as ZoneKey]?.v ?? null
}
